version: "3.9"
services:
  erebrus:
    build: .
    container_name: erebrus
    privileged: true
    environment: 
      LOAD_CONFIG_FILE: "TRUE"
      RUNTYPE: "RUNTYPE"
      SERVER: "0.0.0.0"
      PORT: "9080"
      HTTP_PORT: "8080"
      MASTERNODE_URL: "https://masternode.erebrus.io"
      WG_CONF_DIR: "/etc/wireguard"
      WG_KEYS_DIR: "/etc/wireguard/keys"
      WG_CLIENTS_DIR: "/etc/wireguard/clients"
      WG_INTERFACE_NAME: "wg0.conf"
      WG_ENDPOINT_HOST: "region.erebrus.io"
      WG_ENDPOINT_PORT: "51820"
      WG_IPv4_SUBNET: "fd9f:0000::10:0:0:1/64"
      WG_IPv6_SUBNET: "10.0.0.1/24"
      WG_DNS: "1.1.1.1"
      WG_ALLOWED_IP_1: "0.0.0.0/0"
      WG_ALLOWED_IP_2: "::/0"
      WG_PRE_UP: "echo WireGuard PreUp"
      WG_POST_UP: "iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
      WG_PRE_DOWN: "echo WireGuard PreDown"
      WG_POST_DOWN: "iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE"
    ports:
      - '9080:9080/tcp'
      - '8080:8080/tcp'
    volumes:
      - /etc/erebrus/wireguard:/etc/wireguard
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0